$(function(){
	$(".top_1").bind("mouseover",function(){
		$(".top_2").css({
			display:"block",
		});
	});
	$(".top_1").bind("mouseout",function(){
		$(".top_2").css({
			display:"none"
		});
	});
	$(".right_shop_2").mouseenter(function(){
		$(this).find("div").slideDown(300);
	});
	$(".right_shop_2").mouseleave(function(){
		$(this).find("div").css({
			display:"none"
		});
	});
	$(".right_shop_21").mouseenter(function(){
		$(this).find("div").slideDown(300);
	});
	$(".right_shop_21").mouseleave(function(){
		$(this).find("div").css({
			display:"none"
		});
	});
	$(".right_qq").mouseenter(function(){
		$(".qq_1").css({
			display:"block"
		});
	});
	$(".right_qq").mouseleave(function(){
		$(".qq_1").css({
			display:"none"
		});
	});
	$(".right_top").mouseenter(function(){
		$(".mum_1").css({
			display:"block"
		});
	});
	$(".right_top").mouseleave(function(){
		$(".mum_1").css({
			display:"none"
		});
	});
})
