$(function(){
	$(".top_1").hover(function(){
		$(".top_2").show();
		},function(){
		$(".top_2").hide();
	});
	$(".top_2").hover(function(){
		$(".top_2").show();
		},function(){
		$(".top_2").hide();
	});
	$(".right_shop_2").hover(function(){
		$(this).children("ul").slideDown(300);
		},function(){
			$(this).children("ul").slideUp("fast");
		});
	$(".ul").hover(function(){
			$(this).show();
		},function(){
			$(this).hide();
		});
	$(".right_shop_21").hover(function(){
			$(this).find(".right_shop_yin").show();
			},function(){
			$(this).find(".right_shop_yin").hide();
		});
	
	$(".lb_bottom1").hover(function(){
		$(this).css({
			cursor:"default"
		})
		$(".yinc_1").css({
			display:"none"
		});
		$(".spa").css({
			display:"none"
		});
		$(".bb").css({
			color:"black"
		})
		$(this).find("div").slideDown(200);
		$(this).find("span").css({
			display:"inline-block"
		});
		$(this).find("b").css({
			color:"#a01f23"
		});
	},function(){
		$(this).find("div").css({
			display:"block"
		});
		$(this).find("span").css({
			display:"inline-block"
		});
		$(this).find("b").css({
			color:"#a01f23"
		});
	});
	//判断滚动条的距离
		$(window).scroll(function(){
//		var s=$(window).scrollTop();
//		console.log(s)
		if($(window).scrollTop() >= 500){
		$(".tOp").fadeIn(1000);
		} else{
		$(".tOp").fadeOut(1000);
		}
		});
//		点击返回顶部
		$(".tOp").click(function(){
			$("html,body").animate({scrollTop:0},10);
		})
});
