$(function(){
	$(".top_1").bind("mouseover",function(){
		$(".top_2").css({
			display:"block"
		});
	});
	$(".top_1").bind("mouseout",function(){
		$(".top_2").css({
			display:"none"
		});
	});
	$(".right_shop_2").mouseenter(function(){
		$(this).find("div").slideDown(300);
	});
	$(".right_shop_2").mouseleave(function(){
		$(this).find("div").css({
			display:"none"
		});
	});
	$(".right_shop_21").mouseenter(function(){
		$(this).find("div").slideDown(300);
	});
	$(".right_shop_21").mouseleave(function(){
		$(this).find("div").css({
			display:"none"
		});
	});
	$(".right_qq").mouseenter(function(){
		$(".qq_1").css({
			display:"block"
		});
	});
	$(".right_qq").mouseleave(function(){
		$(".qq_1").css({
			display:"none"
		});
	});
	$(".right_top").mouseenter(function(){
		$(".mum_1").css({
			display:"block"
		});
	});
	$(".right_top").mouseleave(function(){
		$(".mum_1").css({
			display:"none"
		});
	});
	$(".right_mum").mouseenter(function(){
		$(".liBao").css({
			display:"block"
		});
	});
	$(".right_mum").mouseleave(function(){
		$(".liBao").css({
			display:"none"
		});
	});
	$(".lb_bottom1").hover(function(){
		$(this).css({
			cursor:"default"
		})
		$(".yinc_1").css({
			display:"none"
		});
		$(".spa").css({
			display:"none"
		});
		$(".bb").css({
			color:"black"
		})
		$(this).find("div").slideDown(200);
		$(this).find("span").css({
			display:"inline-block"
		});
		$(this).find("b").css({
			color:"#a01f23"
		});
	},function(){
		$(this).find("div").css({
			display:"block"
		});
		$(this).find("span").css({
			display:"inline-block"
		});
		$(this).find("b").css({
			color:"#a01f23"
		});
	});
});
