$(function(){
	$(".top_1").hover(function(){
		$(this).children(".top_show").slideDown(1);
	},function(){
		$(this).children(".top_show").slideUp(1);
	});
	$(".right_shop_21").hover(function(){
		$(this).children(".right_shop_yin").slideDown(100);
	},function(){
		$(this).children(".right_shop_yin").slideUp();
	});
	$(".right_shop_2").hover(function(){
		$(this).children(".shop_yin").slideDown(300);
	},function(){
		$(this).children(".shop_yin").slideUp(100);
	});
	$(".right_qq").mouseenter(function(){
		$(".qq_1").css({
			display:"block"
		});
	});
	$(".right_qq").mouseleave(function(){
		$(".qq_1").css({
			display:"none"
		});
	});
	$(".right_top").mouseenter(function(){
		$(".mum_1").css({
			display:"block"
		});
	});
	$(".right_top").mouseleave(function(){
		$(".mum_1").css({
			display:"none"
		});
	});
	$(".right_mum").mouseenter(function(){
		$(".liBao").css({
			display:"block"
		});
	});
	$(".right_mum").mouseleave(function(){
		$(".liBao").css({
			display:"none"
		});
	});
	
});
